server:
  host: 127.0.0.1
  port: 8085
  timeout:
    server: 34
    read: 15
    write: 10
    idle: 5

entry:
  /:
    data:
      lang: ""
      description: ""
      author: ""
      keyword: ""
      theme: ""
      name: Home
      title: Sea Battle - Home
      attrHTML: {}
      attrBody:
        id: home
        class: home scroll
      path: {}
    files:
      - web\template\page.home.tmpl
      - web\template\partial.header.tmpl
      - web\template\partial.footer.tmpl
      - web\template\layout.base.tmpl
  /about:
    data:
      lang: ""
      description: ""
      author: ""
      keyword: ""
      theme: ""
      name: About
      title: About Us
      attrHTML: {}
      attrBody: {}
      path: {}
    files:
      - web\template\page.about.tmpl
      - web\template\partial.header.tmpl
      - web\template\partial.footer.tmpl
      - web\template\layout.base.tmpl