server:
  host: 127.0.0.1
  port: 8085
  timeout:
    server: 34
    read: 15
    write: 10
    idle: 5

entry:
  /:
    name: Home
    title: Sea Battle - Home
  /about:
    name: About
    title: About Us