common:
  lang: en
  theme: default
  meta:
    description: Sea Battle - multiplayer online game
    author: Oleg Alexandrov
    keyword: SeaBattle,Sea,Battle,Multiplayer,Online,Game
    robots: index, follow
  path:
    img: ../static/img/
    css: ../static/css/
    js:  ../static/js/

entry:
  /:
    data:
      title: Sea Battle - Home
      attrHTML: {}
      attrBody:
        id: home
        class: home scroll
    files:
      - page.home.tmpl
      - partial.header.tmpl
      - partial.footer.tmpl
      - layout.base.tmpl

  /about:
    data:
      title: About Us
      attrHTML: {}
      attrBody:
        id: about
    files:
      - page.about.tmpl
      - partial.header.tmpl
      - partial.footer.tmpl
      - layout.base.tmpl